// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMtvC4Ez0G9r26pQYsnn2VthXvxQKBvh8',
    appId: '1:145892577473:android:9d9ec28f8224d5f40f0440',
    messagingSenderId: '145892577473',
    projectId: 'latihanuts-5f7f9',
    storageBucket: 'latihanuts-5f7f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXq_5CFtztYBm6V_VCwdaXa53GsaJS158',
    appId: '1:145892577473:ios:ba684d42264f940c0f0440',
    messagingSenderId: '145892577473',
    projectId: 'latihanuts-5f7f9',
    storageBucket: 'latihanuts-5f7f9.firebasestorage.app',
    iosBundleId: 'com.example.latihanuts',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEHYb6ZRmLmqmR4SFCdeP9ePdbcSgrsUE',
    appId: '1:145892577473:web:dbb18aaf604f1a1d0f0440',
    messagingSenderId: '145892577473',
    projectId: 'latihanuts-5f7f9',
    authDomain: 'latihanuts-5f7f9.firebaseapp.com',
    storageBucket: 'latihanuts-5f7f9.firebasestorage.app',
    measurementId: 'G-9489DD9PNQ',
    databaseURL: 'https://latihanuts-5f7f9-default-rtdb.firebaseio.com',
  );
}
